[theme_info]
name=SukiBoo
description=Dark color scheme inspired by that nugget.
version=0.5
author=Anton Dereventsov

# Custom colors
#-------------------------------------------------------------------------------
[named_colors]
clr_white	= #ffffff
clr_light	= #aaaaaa
clr_gray	= #606060
clr_dark	= #202020
clr_black	= #000000
clr_pink	= #ff55aa
clr_orange	= #ffaa55
clr_yellow	= #ffff88
clr_green	= #55ffaa
clr_pine 	= #00bb88
clr_cyan	= #88ffff
clr_blue	= #55aaff
clr_purple	= #aa55ff

# format: color;backgroundcolor;bold;italic;

[named_styles]
default		= clr_white;clr_black;false;false;
error		= clr_purple;clr_gray;false;italic;

# Editor styles
#-------------------------------------------------------------------------------

selection		= clr_white;clr_gray;false;true;
current_line		= clr_white;clr_dark;true;
margin_line_number	= clr_light;clr_dark;
margin_folding		= clr_light;clr_dark;
fold_symbol_highlight	= clr_black;
indent_guide		= clr_gray;clr_black;
call_tips		= clr_gray;clr_black;false;false;
white_space		= clr_gray;clr_black;true;false;
caret			= clr_white;clr_white;false;
marker_line		= clr_white;clr_white;
marker_search		= clr_white;clr_white;
marker_mark		= clr_white;clr_white;
brace_good		= clr_cyan;clr_dark;true;false;
brace_bad		= clr_cyan;clr_dark;true;false;


# Programming languages
#-------------------------------------------------------------------------------

comment				= clr_pine;
comment_doc			= clr_green;
comment_line			= comment;
comment_line_doc		= comment_doc;
comment_doc_keyword		= comment_doc,bold;
comment_doc_keyword_error	= comment_doc,italic;

number		= clr_pink;
number_1	= number;
number_2	= number;

type		= clr_yellow;clr_black;true;false;
class		= type;
function	= clr_orange;clr_black;true;false;
parameter	= function;

keyword		= clr_yellow;clr_black;true;false;
keyword_1	= keyword;
keyword_2	= clr_orange;clr_black;true;false;
keyword_3	= keyword;
keyword_4	= keyword;

identifier	= default;
identifier_1	= identifier;
identifier_2	= identifier;
identifier_3	= identifier;
identifier_4	= identifier;

string		= clr_blue;
string_1	= string;
string_2	= clr_purple;
string_eol	= clr_white;clr_white;false;false;
character	= string_1;
backticks	= string_2;
here_doc	= string_2;

label		= default,bold;
preprocessor	= clr_pink;
regex		= number_1;
operator	= clr_pink;clr_black;true;
decorator	= string_1,bold;
other		= clr_orange;

# Markup-type languages
#-------------------------------------------------------------------------------

tag			= type;
tag_unknown		= tag,bold;
tag_end			= tag,bold;
attribute		= keyword_1;
attribute_unknown	= attribute,bold;
value			= string;
entity			= default;

# Diff
#-------------------------------------------------------------------------------

line_added	= clr_green;clr_black;false;false;
line_removed	= clr_pink;clr_black;false;false;
line_changed	= clr_cyan;clr_black;false;false;

